# # Create a storage class from microk8s default host storage class
# # that allows data retention and volume expansion.
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: media-storage
# provisioner: microk8s.io/hostpath
# reclaimPolicy: Retain
# allowVolumeExpansion: True
---
# Create a persistent volume to mount local media folder into container
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    volume-type: media-volume
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadOnlyMany
  claimRef:
    kind: PersistentVolumeClaim
    name: media-pvc
    namespace: jellyfin
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/media
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  storageClassName: microk8s-hostpath
  volumeName: media-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Ti
